import Head from "next/head";
import React, { useState, useEffect } from "react";
import style from "../styles/Home.module.css";
import Post from "../components/Post";
import CriteriaSet from "../components/CriteriaSet";
import axios from "axios";

export default function Home() {
  const [posts, setPosts] = useState([]);
  const [criteria, setCriteria] = useState("");

  useEffect(() => {
    axios
      .get("/api" + criteria)
      .then((data) => {
        data.data.length > 0
          ? setPosts(data.data)
          : setPosts([
              {
                author: "",
                subject: "",
                body: "No posts found",
                date: "",
              },
            ]);
      })
      .catch((err) => {
        if (err.response.status === 404)
          setPosts([
            {
              author: "",
              subject: "",
              body: "No posts found",
              date: "",
            },
          ]);
        console.log({
          error: err,
        });
      });
    return () => {
      console.log("Cleanup");
    };
  }, [criteria]);

  return (
    <div className={style.container}>
      <Head>
        <title>Paradox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={style.upperSection}>
        <h1 className={style.title}> Paradox! is it real?</h1>
        <CriteriaSet criteria={criteria} setCriteria={setCriteria} />
      </section>
      <section className={style.lowerSection}>
        {posts.map((post, id) => (
          <Post {...post} key={id} />
        ))}
      </section>
    </div>
  );
}
